/*
Copyright (c) 2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.gl.context;

import dcore.linker;
import dcore.gl.types;
import dcore.gl.gles20;
import dcore.gl.gles30;

enum WGL_CONTEXT_MAJOR_VERSION_ARB = 0x2091;
enum WGL_CONTEXT_MINOR_VERSION_ARB = 0x2092;
enum WGL_CONTEXT_PROFILE_MASK_ARB = 0x9126;

enum WGL_CONTEXT_ES_PROFILE_BIT_EXT = 0x00000004;
enum WGL_CONTEXT_ES2_PROFILE_BIT_EXT = 0x00000004;

enum WGL_CONTEXT_CORE_PROFILE_BIT_ARB = 0x00000001;
enum WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB = 0x00000002;

struct OpenGLVersion
{
    int major;
    int minor;
    int profile;
}

enum
{
    OpenGL20 = OpenGLVersion(2, 0, 0),
    OpenGL30 = OpenGLVersion(3, 0, 0),
    OpenGL31 = OpenGLVersion(3, 1, 0),
    OpenGL32 = OpenGLVersion(3, 2, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL33 = OpenGLVersion(3, 3, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL40 = OpenGLVersion(4, 0, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL41 = OpenGLVersion(4, 1, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL42 = OpenGLVersion(4, 2, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL43 = OpenGLVersion(4, 3, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL44 = OpenGLVersion(4, 4, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL45 = OpenGLVersion(4, 5, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGL46 = OpenGLVersion(4, 6, WGL_CONTEXT_CORE_PROFILE_BIT_ARB),
    OpenGLES20 = OpenGLVersion(2, 0, WGL_CONTEXT_ES2_PROFILE_BIT_EXT),
    OpenGLES30 = OpenGLVersion(3, 0, WGL_CONTEXT_ES2_PROFILE_BIT_EXT),
    OpenGLES31 = OpenGLVersion(3, 1, WGL_CONTEXT_ES2_PROFILE_BIT_EXT),
    OpenGLES32 = OpenGLVersion(3, 2, WGL_CONTEXT_ES2_PROFILE_BIT_EXT)
}

version(Windows)
{
    import core.sys.windows.windows;
    
    extern(Windows) @nogc nothrow
    {
        alias f_wglCopyContext = BOOL function(HGLRC, HGLRC, uint);
        alias f_wglCreateContext = HGLRC function(HDC);
        alias f_wglCreateLayerContext = HGLRC function(HDC, int);
        alias f_wglDeleteContext = BOOL function(HGLRC);
        alias f_wglDescribeLayerPlane = BOOL function(HDC, int, int, uint, LPLAYERPLANEDESCRIPTOR);
        alias f_wglGetCurrentContext = HGLRC function();
        alias f_wglGetCurrentDC = HDC function();
        alias f_wglGetLayerPaletteEntries = int function(HDC, int, int, int, COLORREF*);
        alias f_wglGetProcAddress = PROC function(LPCSTR);
        alias f_wglMakeCurrent = BOOL function(HDC, HGLRC);
        alias f_wglRealizeLayerPalette = BOOL function(HDC, int, BOOL);
        alias f_wglSetLayerPaletteEntries = int function(HDC, int, int, int, const(COLORREF)*);
        alias f_wglShareLists = BOOL function(HGLRC, HGLRC);
        alias f_wglSwapLayerBuffers = BOOL function(HDC, UINT);
        alias f_wglUseFontBitmaps = BOOL function(HDC, DWORD, DWORD, DWORD);
        alias f_wglUseFontOutlines = BOOL function(HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, int, LPGLYPHMETRICSFLOAT);
        alias f_wglCreateContextAttribsARB = HGLRC function(HDC hDC, HGLRC hShareContext, const(int)* attribList);
    }
    
    __gshared
    {
        f_wglCopyContext wglCopyContext;
        f_wglCreateContext wglCreateContext;
        f_wglCreateLayerContext wglCreateLayerContext;
        f_wglDeleteContext wglDeleteContext;
        f_wglDescribeLayerPlane wglDescribeLayerPlane;
        f_wglGetCurrentContext wglGetCurrentContext;
        f_wglGetCurrentDC wglGetCurrentDC;
        f_wglGetLayerPaletteEntries wglGetLayerPaletteEntries;
        f_wglGetProcAddress wglGetProcAddress;
        f_wglMakeCurrent wglMakeCurrent;
        f_wglRealizeLayerPalette wglRealizeLayerPalette;
        f_wglSetLayerPaletteEntries wglSetLayerPaletteEntries;
        f_wglShareLists wglShareLists;
        f_wglSwapLayerBuffers wglSwapLayerBuffers;
        f_wglUseFontBitmaps wglUseFontBitmapsA;
        f_wglUseFontBitmaps wglUseFontBitmapsW;
        f_wglUseFontOutlines wglUseFontOutlinesA;
        f_wglUseFontOutlines wglUseFontOutlinesW;
        f_wglCreateContextAttribsARB wglCreateContextAttribsARB;
    }
}
else version(Posix)
{
    import core.sys.posix.dlfcn;
}

__gshared
{
    private SharedLib libogl;
}

private void* loadGLProc(const(char)* name) @nogc nothrow
{
    pragma(inline, true);
    
    version(Windows)
    {
        void* p = wglGetProcAddress(name);
        if (p !is null)
             return p;
        return getFunctionPointer(libogl, name);
    }
    else version(Posix)
    {
        return getFunctionPointer(libogl, name);
    }
    else
    {
        pragma(msg, "Warning: \"loadGLProc\" is not implemented on this platform!");
        return null;
    }
}

version(Windows)
{
    enum OpenGLLibraryName = "Opengl32.dll";
}
else version(Posix)
{
    // TODO
}

void init() @nogc nothrow
{
    version(Windows)
    {
        libogl = openLibrary(OpenGLLibraryName);
        wglCopyContext = cast(f_wglCopyContext)getFunctionPointer(libogl, "wglCopyContext");
        wglCreateContext = cast(f_wglCreateContext)getFunctionPointer(libogl, "wglCreateContext");
        wglCreateLayerContext = cast(f_wglCreateLayerContext)getFunctionPointer(libogl, "wglCreateLayerContext");
        wglDeleteContext = cast(f_wglDeleteContext)getFunctionPointer(libogl, "wglDeleteContext");
        wglDescribeLayerPlane = cast(f_wglDescribeLayerPlane)getFunctionPointer(libogl, "wglDescribeLayerPlane");
        wglGetCurrentContext = cast(f_wglGetCurrentContext)getFunctionPointer(libogl, "wglGetCurrentContext");
        wglGetCurrentDC = cast(f_wglGetCurrentDC)getFunctionPointer(libogl, "wglGetCurrentDC");
        wglGetLayerPaletteEntries = cast(f_wglGetLayerPaletteEntries)getFunctionPointer(libogl, "wglGetLayerPaletteEntries");
        wglGetProcAddress = cast(f_wglGetProcAddress)getFunctionPointer(libogl, "wglGetProcAddress");
        wglMakeCurrent = cast(f_wglMakeCurrent)getFunctionPointer(libogl, "wglMakeCurrent");
        wglRealizeLayerPalette = cast(f_wglRealizeLayerPalette)getFunctionPointer(libogl, "wglRealizeLayerPalette");
        wglSetLayerPaletteEntries = cast(f_wglSetLayerPaletteEntries)getFunctionPointer(libogl, "wglSetLayerPaletteEntries");
        wglShareLists = cast(f_wglShareLists)getFunctionPointer(libogl, "wglShareLists");
        wglSwapLayerBuffers = cast(f_wglSwapLayerBuffers)getFunctionPointer(libogl, "wglSwapLayerBuffers");
        wglUseFontBitmapsA = cast(f_wglUseFontBitmaps)getFunctionPointer(libogl, "wglUseFontBitmapsA");
        wglUseFontBitmapsW = cast(f_wglUseFontBitmaps)getFunctionPointer(libogl, "wglUseFontBitmapsW");
        wglUseFontOutlinesA = cast(f_wglUseFontOutlines)getFunctionPointer(libogl, "wglUseFontOutlinesA");
        wglUseFontOutlinesW = cast(f_wglUseFontOutlines)getFunctionPointer(libogl, "wglUseFontOutlinesW");
    }
    else version(Posix)
    {
        libogl = openLibrary("libGL.so.1", RTLD_LAZY);
        
        // TODO
    }
    else version(WebAssembly)
    {
        // TODO
    }
}

version(Windows)
{
    private HGLRC loadOpenGL_Windows(HDC hdc, OpenGLVersion oglv)
    {
        PIXELFORMATDESCRIPTOR pfd;
        pfd.nSize = PIXELFORMATDESCRIPTOR.sizeof;
        pfd.nVersion = 1;
        pfd.dwFlags = PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER;
        pfd.iPixelType = PFD_TYPE_RGBA;
        pfd.cColorBits = 32;
        pfd.cDepthBits = 32;
        pfd.iLayerType = PFD_MAIN_PLANE;
        int pixelFormat = ChoosePixelFormat(hdc, &pfd);
        SetPixelFormat(hdc, pixelFormat, &pfd);
        
        HGLRC tmpGlContext = wglCreateContext(hdc);
        if (tmpGlContext is null)
            return null;
        
        wglMakeCurrent(hdc, tmpGlContext);
        wglCreateContextAttribsARB = cast(f_wglCreateContextAttribsARB)wglGetProcAddress("wglCreateContextAttribsARB");

        int[7] attribs = [
            WGL_CONTEXT_MAJOR_VERSION_ARB, oglv.major,
            WGL_CONTEXT_MINOR_VERSION_ARB, oglv.minor,
            WGL_CONTEXT_PROFILE_MASK_ARB, oglv.profile,
            0
        ];

        HGLRC glesContext = wglCreateContextAttribsARB(hdc, null, attribs.ptr);
        if (glesContext is null)
            return null;
        
        wglMakeCurrent(hdc, null);
        wglDeleteContext(tmpGlContext);
        wglMakeCurrent(hdc, glesContext);
        
        loadOpenGLFunctions(oglv);
        
        return glesContext;
    }
}
else version(Posix)
{
    // TODO
}

void* loadOpenGL(void* deviceContext, OpenGLVersion oglv)
{
    pragma(inline, true);
    version(Windows)
    {
        return loadOpenGL_Windows(deviceContext, oglv);
    }
    else version(Posix)
    {
        // TODO
        pragma(msg, "Warning: \"loadOpenGL\" is not implemented on this platform!");
        return null;
    }
    else
    {
        pragma(msg, "Warning: \"loadOpenGL\" is not implemented on this platform!");
        return null;
    }
}

void bindGLSymbol(void** symbolPtr, const(char)* name)
{
    *symbolPtr = loadGLProc(name);
}

void loadOpenGLFunctions(OpenGLVersion oglv)
{
    if (oglv.major >= 2)
    {
        static foreach(symbol; __traits(allMembers, dcore.gl.gles20))
        {
            static if (symbol.length > 2 && symbol[0..2] == "gl")
                bindGLSymbol(
                    cast(void**)&__traits(getMember, dcore.gl.gles20, symbol),
                    __traits(getMember, dcore.gl.gles20, symbol).stringof);
        }
    }
    
    if (oglv.major >= 3)
    {
        static foreach(symbol; __traits(allMembers, dcore.gl.gles30))
        {
            static if (symbol.length > 2 && symbol[0..2] == "gl")
                bindGLSymbol(
                    cast(void**)&__traits(getMember, dcore.gl.gles30, symbol),
                    __traits(getMember, dcore.gl.gles30, symbol).stringof);
        }
    }
}
