/*
Copyright (c) 2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.gl.funcs;

import dcore.gl.signatures;

__gshared
{
    f_glActiveTexture glActiveTexture;
    f_glAttachShader glAttachShader;
    
    f_glBindAttribLocation glBindAttribLocation;
    f_glBindBuffer glBindBuffer;
    f_glBindFramebuffer glBindFramebuffer;
    f_glBindRenderbuffer glBindRenderbuffer;
    f_glBindTexture glBindTexture;
    f_glBindVertexArray glBindVertexArray;
    f_glBlendColor glBlendColor;
    f_glBlendEquation glBlendEquation;
    f_glBlendEquationSeparate glBlendEquationSeparate;
    f_glBlendFunc glBlendFunc;
    f_glBlendFuncSeparate glBlendFuncSeparate;
    f_glBufferData glBufferData;
    f_glBufferSubData glBufferSubData;
    
    f_glCheckFramebufferStatus glCheckFramebufferStatus;
    f_glClear glClear;
    f_glClearColor glClearColor;
    f_glClearDepthf glClearDepthf;
    f_glClearStencil glClearStencil;
    f_glCompileShader glCompileShader;
    f_glCreateProgram glCreateProgram;
    f_glCreateShader glCreateShader;
    
    f_glDepthFunc glDepthFunc;
    f_glDisable glDisable;
    f_glDrawElements glDrawElements;
    
    f_glEnable glEnable;
    f_glEnableVertexAttribArray glEnableVertexAttribArray;
    
    f_glFlush glFlush;
    
    f_glGenBuffers glGenBuffers;
    f_glGenVertexArrays glGenVertexArrays;
    f_glGetUniformLocation glGetUniformLocation;
    
    f_glLinkProgram glLinkProgram;
    
    f_glShaderSource glShaderSource;
    
    f_glUniformMatrix4fv glUniformMatrix4fv;
    f_glUseProgram glUseProgram;
    
    f_glVertexAttribPointer glVertexAttribPointer;
    f_glViewport glViewport;
}
