/*
Copyright (c) 2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.gl.gles20;

import dcore.gl.signatures;

__gshared
{
    f_glActiveTexture glActiveTexture;
    f_glAttachShader glAttachShader;
    
    f_glBindAttribLocation glBindAttribLocation;
    f_glBindBuffer glBindBuffer;
    f_glBindFramebuffer glBindFramebuffer;
    f_glBindRenderbuffer glBindRenderbuffer;
    f_glBindTexture glBindTexture;
    f_glBindVertexArray glBindVertexArray;
    f_glBlendColor glBlendColor;
    f_glBlendEquation glBlendEquation;
    f_glBlendEquationSeparate glBlendEquationSeparate;
    f_glBlendFunc glBlendFunc;
    f_glBlendFuncSeparate glBlendFuncSeparate;
    f_glBufferData glBufferData;
    f_glBufferSubData glBufferSubData;
    
    f_glCheckFramebufferStatus glCheckFramebufferStatus;
    f_glClear glClear;
    f_glClearColor glClearColor;
    f_glClearDepthf glClearDepthf;
    f_glClearStencil glClearStencil;
    f_glColorMask glColorMask;
    f_glCompileShader glCompileShader;
    f_glCompressedTexImage2D glCompressedTexImage2D;
    f_glCompressedTexSubImage2D glCompressedTexSubImage2D;
    f_glCopyTexImage2D glCopyTexImage2D;
    f_glCopyTexSubImage2D glCopyTexSubImage2D;
    f_glCreateProgram glCreateProgram;
    f_glCreateShader glCreateShader;
    f_glCullFace glCullFace;
    
    f_glDeleteBuffers glDeleteBuffers;
    f_glDeleteFramebuffers glDeleteFramebuffers;
    f_glDeleteProgram glDeleteProgram;
    f_glDeleteRenderbuffers glDeleteRenderbuffers;
    f_glDeleteShader glDeleteShader;
    f_glDeleteTextures glDeleteTextures;
    f_glDepthFunc glDepthFunc;
    f_glDepthMask glDepthMask;
    f_glDepthRangef glDepthRangef;
    f_glDetachShader glDetachShader;
    f_glDisable glDisable;
    f_glDisableVertexAttribArray glDisableVertexAttribArray;
    f_glDrawArrays glDrawArrays;
    f_glDrawElements glDrawElements;
    
    f_glEnable glEnable;
    f_glEnableVertexAttribArray glEnableVertexAttribArray;
    
    f_glFinish glFinish;
    f_glFlush glFlush;
    f_glFramebufferRenderbuffer glFramebufferRenderbuffer;
    f_glFramebufferTexture2D glFramebufferTexture2D;
    f_glFrontFace glFrontFace;
    f_glGenBuffers glGenBuffers;
    f_glGenerateMipmap glGenerateMipmap;
    f_glGenFramebuffers glGenFramebuffers;
    f_glGenRenderbuffers glGenRenderbuffers;
    f_glGenTextures glGenTextures;
    
    f_glGetUniformLocation glGetUniformLocation;
    
    f_glLinkProgram glLinkProgram;
    
    f_glShaderSource glShaderSource;
    
    f_glUniformMatrix4fv glUniformMatrix4fv;
    f_glUseProgram glUseProgram;
    
    f_glValidateProgram glValidateProgram;
    f_glVertexAttrib1f glVertexAttrib1f;
    f_glVertexAttrib1fv glVertexAttrib1fv;
    f_glVertexAttrib2f glVertexAttrib2f;
    f_glVertexAttrib2fv glVertexAttrib2fv;
    f_glVertexAttrib3f glVertexAttrib3f;
    f_glVertexAttrib3fv glVertexAttrib3fv;
    f_glVertexAttrib4f glVertexAttrib4f;
    f_glVertexAttrib4fv glVertexAttrib4fv;
    
    f_glVertexAttribPointer glVertexAttribPointer;
    f_glViewport glViewport;
}
