/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.gl.gles30;

import dcore.gl.signatures;

__gshared
{
    f_glReadBuffer glReadBuffer;
    f_glDrawRangeElements glDrawRangeElements;
    f_glTexImage3D glTexImage3D;
    f_glTexSubImage3D glTexSubImage3D;
    f_glCopyTexSubImage3D glCopyTexSubImage3D;
    f_glCompressedTexImage3D glCompressedTexImage3D;
    f_glCompressedTexSubImage3D glCompressedTexSubImage3D;
    f_glGenQueries glGenQueries;
    f_glDeleteQueries glDeleteQueries;
    f_glIsQuery glIsQuery;
    f_glBeginQuery glBeginQuery;
    f_glEndQuery glEndQuery;
    f_glGetQueryiv glGetQueryiv;
    f_glGetQueryObjectuiv glGetQueryObjectuiv;
    f_glUnmapBuffer glUnmapBuffer;
    f_glGetBufferPointerv glGetBufferPointerv;
    f_glDrawBuffers glDrawBuffers;
    f_glUniformMatrix2x3fv glUniformMatrix2x3fv;
    f_glUniformMatrix3x2fv glUniformMatrix3x2fv;
    f_glUniformMatrix2x4fv glUniformMatrix2x4fv;
    f_glUniformMatrix4x2fv glUniformMatrix4x2fv;
    f_glUniformMatrix3x4fv glUniformMatrix3x4fv;
    f_glUniformMatrix4x3fv glUniformMatrix4x3fv;
    f_glBlitFramebuffer glBlitFramebuffer;
    f_glRenderbufferStorageMultisample glRenderbufferStorageMultisample;
    f_glFramebufferTextureLayer glFramebufferTextureLayer;
    f_glMapBufferRange glMapBufferRange;
    f_glFlushMappedBufferRange glFlushMappedBufferRange;
    f_glBindVertexArray glBindVertexArray;
    f_glDeleteVertexArrays glDeleteVertexArrays;
    f_glGenVertexArrays glGenVertexArrays;
    
    // TODO
}
