/*
Copyright (c) 2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.gl.signatures;

import dcore.gl.types;

extern(System) @nogc nothrow:

// GLES 2.0

alias f_glActiveTexture = void function(GLenum texture);
alias f_glAttachShader = void function(GLuint program, GLuint shader);

alias f_glBindAttribLocation = void function(GLuint program, GLuint index, const(GLchar)* name);
alias f_glBindBuffer = void function(GLenum target, GLuint buffer);
alias f_glBindFramebuffer = void function(GLenum target, GLuint framebuffer);
alias f_glBindRenderbuffer = void function(GLenum target, GLuint renderbuffer);
alias f_glBindTexture = void function(GLenum target, GLuint texture);
alias f_glBindVertexArray = void function(GLuint array);
alias f_glBlendColor = void function(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
alias f_glBlendEquation = void function(GLenum mode);
alias f_glBlendEquationSeparate = void function(GLenum modeRGB, GLenum modeAlpha);
alias f_glBlendFunc = void function(GLenum sfactor, GLenum dfactor);
alias f_glBlendFuncSeparate = void function(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
alias f_glBufferData = void function(GLenum target, GLsizeiptr size, const(void)* data, GLenum usage);
alias f_glBufferSubData = void function(GLenum target, GLintptr offset, GLsizeiptr size, const(void)* data);

alias f_glCheckFramebufferStatus = GLenum function(GLenum target);
alias f_glClear = void function(GLenum mask);
alias f_glClearColor = void function(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
alias f_glClearDepthf = void function(GLfloat d);
alias f_glClearStencil = void function(GLint s);
alias f_glColorMask = void function(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
alias f_glCompileShader = void function(GLuint shader);
alias f_glCompressedTexImage2D = void function(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const(void)* data);
alias f_glCompressedTexSubImage2D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const(void)* data);
alias f_glCopyTexImage2D = void function(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
alias f_glCopyTexSubImage2D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
alias f_glCreateProgram = GLuint function();
alias f_glCreateShader = GLuint function(GLenum type);
alias f_glCullFace = void function(GLenum mode);

alias f_glDeleteBuffers = void function(GLsizei n, const(GLuint)* buffers);
alias f_glDeleteFramebuffers = void function(GLsizei n, const(GLuint)* framebuffers);
alias f_glDeleteProgram = void function(GLuint program);
alias f_glDeleteRenderbuffers = void function(GLsizei n, const(GLuint)* renderbuffers);
alias f_glDeleteShader = void function(GLuint shader);
alias f_glDeleteTextures = void function(GLsizei n, const(GLuint)* textures);
alias f_glDepthFunc = void function(GLenum func);
alias f_glDepthMask = void function(GLboolean flag);
alias f_glDepthRangef = void function(GLfloat n, GLfloat f);
alias f_glDetachShader = void function(GLuint program, GLuint shader);
alias f_glDisable = void function(GLenum cap);
alias f_glDisableVertexAttribArray = void function(GLuint index);
alias f_glDrawArrays = void function(GLenum mode, GLint first, GLsizei count);
alias f_glDrawElements = void function(GLenum mode, GLsizei count, GLenum type, const(void)* indices);

alias f_glEnable = void function(GLenum cap);
alias f_glEnableVertexAttribArray = void function(GLuint index);

alias f_glFinish = void function();
alias f_glFlush = void function();
alias f_glFramebufferRenderbuffer = void function(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
alias f_glFramebufferTexture2D = void function(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
alias f_glFrontFace = void function(GLenum mode);

alias f_glGenBuffers = void function(GLsizei n, GLuint* buffers);
alias f_glGenerateMipmap = void function(GLenum target);
alias f_glGenFramebuffers = void function(GLsizei n, GLuint* framebuffers);
alias f_glGenRenderbuffers = void function(GLsizei n, GLuint* renderbuffers);
alias f_glGenTextures = void function(GLsizei n, GLuint* textures);
alias f_glGetActiveAttrib = void function(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
alias f_glGetActiveUniform = void function(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
alias f_glGetAttachedShaders = void function(GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders);
alias f_glGetAttribLocation = GLint function(GLuint program, const(GLchar)* name);
alias f_glGetBooleanv = void function(GLenum pname, GLboolean* data);
alias f_glGetBufferParameteriv = void function(GLenum target, GLenum pname, GLint* params);
alias f_glGetError = GLenum function();
alias f_glGetFloatv = void function(GLenum pname, GLfloat* data);
alias f_glGetFramebufferAttachmentParameteriv = void function(GLenum target, GLenum attachment, GLenum pname, GLint* params);
alias f_glGetIntegerv = void function(GLenum pname, GLint* data);
alias f_glGetProgramiv = void function(GLuint program, GLenum pname, GLint* params);
alias f_glGetProgramInfoLog = void function(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
alias f_glGetRenderbufferParameteriv = void function(GLenum target, GLenum pname, GLint* params);
alias f_glGetShaderiv = void function(GLuint shader, GLenum pname, GLint* params);
alias f_glGetShaderInfoLog = void function(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
alias f_glGetShaderPrecisionFormat = void function(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
alias f_glGetShaderSource = void function(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* source);
alias f_glGetString = const(GLubyte)* function(GLenum name);
alias f_glGetTexParameterfv = void function(GLenum target, GLenum pname, GLfloat* params);
alias f_glGetTexParameteriv = void function(GLenum target, GLenum pname, GLint* params);
alias f_glGetUniformfv = void function(GLuint program, GLint location, GLfloat* params);
alias f_glGetUniformiv = void function(GLuint program, GLint location, GLint* params);
alias f_glGetUniformLocation = GLint function(GLuint program, const(GLchar)* name);
alias f_glGetVertexAttribfv = void function(GLuint index, GLenum pname, GLfloat* params);
alias f_glGetVertexAttribiv = void function(GLuint index, GLenum pname, GLint* params);
alias f_glGetVertexAttribPointerv = void function(GLuint index, GLenum pname, void** pointer);

alias f_glHint = void function(GLenum target, GLenum mode);

alias f_glIsBuffer = GLboolean function(GLuint buffer);
alias f_glIsEnabled = GLboolean function(GLenum cap);
alias f_glIsFramebuffer = GLboolean function(GLuint framebuffer);
alias f_glIsProgram = GLboolean function(GLuint program);
alias f_glIsRenderbuffer = GLboolean function(GLuint renderbuffer);
alias f_glIsShader = GLboolean function(GLuint shader);
alias f_glIsTexture = GLboolean function(GLuint texture);

alias f_glLineWidth = void function(GLfloat width);
alias f_glLinkProgram = void function(GLuint program);

alias f_glPixelStorei = void function(GLenum pname, GLint param);
alias f_glPolygonOffset = void function(GLfloat factor, GLfloat units);

alias f_glReadPixels = void function(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
alias f_glReleaseShaderCompiler = void function();
alias f_glRenderbufferStorage = void function(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);

alias f_glSampleCoverage = void function(GLfloat value, GLboolean invert);
alias f_glScissor = void function(GLint x, GLint y, GLsizei width, GLsizei height);
alias f_glShaderBinary = void function(GLsizei count, const(GLuint)* shaders, GLenum binaryFormat, const(void)* binary, GLsizei length);
alias f_glShaderSource = void function(GLuint shader, GLsizei count, const(const(GLchar)*)* str, const(GLint)* length);
alias f_glStencilFunc = void function(GLenum func, GLint refValue, GLuint mask);
alias f_glStencilFuncSeparate = void function(GLenum face, GLenum func, GLint refValue, GLuint mask);
alias f_glStencilMask = void function(GLuint mask);
alias f_glStencilMaskSeparate = void function(GLenum face, GLuint mask);
alias f_glStencilOp = void function(GLenum fail, GLenum zfail, GLenum zpass);
alias f_glStencilOpSeparate = void function(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);

alias f_glTexImage2D = void function(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const(void)* pixels);
alias f_glTexParameterf = void function(GLenum target, GLenum pname, GLfloat param);
alias f_glTexParameterfv = void function(GLenum target, GLenum pname, const(GLfloat)* params);
alias f_glTexParameteri = void function(GLenum target, GLenum pname, GLint param);
alias f_glTexParameteriv = void function(GLenum target, GLenum pname, const(GLint)* params);
alias f_glTexSubImage2D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const(void)* pixels);

alias f_glUniform1f = void function(GLint location, GLfloat v0);
alias f_glUniform1fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform1i = void function(GLint location, GLint v0);
alias f_glUniform1iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniform2f = void function(GLint location, GLfloat v0, GLfloat v1);
alias f_glUniform2fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform2i = void function(GLint location, GLint v0, GLint v1);
alias f_glUniform2iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniform3f = void function(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
alias f_glUniform3fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform3i = void function(GLint location, GLint v0, GLint v1, GLint v2);
alias f_glUniform3iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniform4f = void function(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
alias f_glUniform4fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform4i = void function(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
alias f_glUniform4iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniformMatrix2fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix3fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix4fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUseProgram = void function(GLuint program);

alias f_glValidateProgram = void function(GLuint program);
alias f_glVertexAttrib1f = void function(GLuint index, GLfloat x);
alias f_glVertexAttrib1fv = void function(GLuint index, const(GLfloat)* v);
alias f_glVertexAttrib2f = void function(GLuint index, GLfloat x, GLfloat y);
alias f_glVertexAttrib2fv = void function(GLuint index, const(GLfloat)* v);
alias f_glVertexAttrib3f = void function(GLuint index, GLfloat x, GLfloat y, GLfloat z);
alias f_glVertexAttrib3fv = void function(GLuint index, const(GLfloat)* v);
alias f_glVertexAttrib4f = void function(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
alias f_glVertexAttrib4fv = void function(GLuint index, const(GLfloat)* v);

alias f_glVertexAttribPointer = void function(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const(void)* pointer);
alias f_glViewport = void function(GLint x, GLint y, GLsizei width, GLsizei height);

// GLES 3.0

// TODO

alias f_glGenVertexArrays = void function(GLsizei n, GLuint* arrays);
