/*
Copyright (c) 2025 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.windows;

public import dcore.windows.timer;

version(Windows):

public import core.sys.windows.windows;

enum WindowStateSignal
{
    None = 0,
    Resize = 1
}

struct WindowState
{
    int width;
    int height;
    const(wchar)* title;
    WindowStateSignal ss;
}

extern(Windows) LRESULT WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) nothrow
{
    if (msg == WM_NCCREATE)
    {
        auto createStruct = cast(CREATESTRUCT*)lParam;
        auto windowState = cast(WindowState*)createStruct.lpCreateParams;
        SetWindowLongPtr(hwnd, GWLP_USERDATA, cast(LONG_PTR)windowState);
        return TRUE;
    }
    
    auto windowState = cast(WindowState*)GetWindowLongPtr(hwnd, GWLP_USERDATA);
    if (windowState is null)
        return DefWindowProc(hwnd, msg, wParam, lParam);
    
    switch (msg)
    {
        case WM_DESTROY:
            PostQuitMessage(0);
            return 0;
        case WM_SIZE:
            windowState.width = lParam & 0xFFFF;
            windowState.height = cast(int)(lParam >> 16);
            windowState.ss = WindowStateSignal.Resize;
            return 0;
        default:
            break;
    }
    return DefWindowProc(hwnd, msg, wParam, lParam);
}

HWND createWindow(uint width, uint height, const(wchar)* title, WindowState* windowState)
{
    WNDCLASS wc;
    wc.style = 0;
    wc.lpfnWndProc = &DefWindowProc;
    wc.cbClsExtra = 0;
    wc.cbWndExtra = 0;
    wc.hInstance = GetModuleHandle(null);
    wc.hIcon = null;
    wc.hCursor = LoadCursor(null, IDC_ARROW);
    wc.hbrBackground = cast(HBRUSH)(COLOR_WINDOW + 1);
    wc.lpszMenuName = null;
    wc.lpszClassName = "DcoreWindow";
    wc.lpfnWndProc = &WndProc;

    if (RegisterClass(&wc) == 0)
    {
        return null;
    }

    HWND hwnd = CreateWindowExW(
        0,
        wc.lpszClassName,
        title,
        WS_OVERLAPPEDWINDOW | WS_VISIBLE | WS_CLIPSIBLINGS | WS_CLIPCHILDREN,
        100, 100, 800, 600,
        null, null, wc.hInstance, windowState
    );
    
    return hwnd;
}

private
{
    __gshared MSG w_msg;
}

alias EventDispatchCallback = void function(MSG*, void*);

void dispatchMessage(EventDispatchCallback callback, void* userData)
{
    while (PeekMessage(&w_msg, null, 0, 0, PM_REMOVE) != 0)
    {
        if (callback)
            callback(&w_msg, userData);
        TranslateMessage(&w_msg);
        DispatchMessage(&w_msg);
    }
}
