/*
Copyright (c) 2024-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.random;

version(WebAssembly)
{
    version = UseFreeStandingRNG;
}
else version(FreeStanding)
{
    version = UseFreeStandingRNG;
}

/**
 * Bob Jenkins' 96 bit mix function
 */
ulong mix(ulong a, ulong b, ulong c) pure nothrow @nogc
{
    a=a-b;  a=a-c;  a=a^(c >> 13);
    b=b-c;  b=b-a;  b=b^(a << 8);
    c=c-a;  c=c-b;  c=c^(b >> 13);
    a=a-b;  a=a-c;  a=a^(c >> 12);
    b=b-c;  b=b-a;  b=b^(a << 16);
    c=c-a;  c=c-b;  c=c^(b >> 5);
    a=a-b;  a=a-c;  a=a^(c >> 3);
    b=b-c;  b=b-a;  b=b^(a << 10);
    c=c-a;  c=c-b;  c=c^(b >> 15);
    return c;
}

/// Simple 64-bit xorshift PRNG
struct RNG
{
    ulong state;

    /// Initialize with a seed
    void init(ulong s) nothrow @nogc
    {
        state = s;
        if (state == 0) state = 0xdeadbeefcafebabeUL; // avoid zero seed
    }

    /// Generate next random 64-bit unsigned integer
    ulong nextULong() nothrow @nogc
    {
        ulong x = state;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        state = x;
        return x * 0x2545F4914F6CDD1DUL;
    }

    /// Generate next random integer in [mi, ma)
    int randomInRange(int mi, int ma) nothrow @nogc
    {
        ulong r = nextULong();
        return mi + cast(int)(r % cast(ulong)(ma - mi));
    }

    /// Generate next random floating-point number in [0,1)
    T random(T)() nothrow @nogc
    {
        return cast(T)(nextULong() >> 11) / cast(T)(1UL << 53); // 53-bit precision
    }
}

version(UseFreeStandingRNG)
{
    private __gshared RNG rng;
    
    void init() nothrow @nogc
    {
        pragma(inline, true);
        rng.init(seed());
    }
    
    version(X86_64)
    {
        ulong rdtsc() nothrow @nogc
        {
            ulong lo, hi;
            asm nothrow @nogc
            {
                rdtsc;
                mov lo, EAX;
                mov hi, EDX;
            }
            return (hi << 32) | lo;
        }
        
        alias seed = rdtsc;
    }
    else
    {
        ulong seed() nothrow @nogc
        {
            ulong x;
            ulong y = cast(ulong)cast(byte*)__FUNCTION__;
            return mix(cast(ulong)&x, y, 0xDEADBEEFDEADBEEFUL);
        }
    }
    
    void setSeed(ulong s) nothrow @nogc
    {
        pragma(inline, true);
        rng.init(s);
    }

    int randomInRange(int mi, int ma) nothrow @nogc
    {
        pragma(inline, true);
        return rng.randomInRange(mi, ma);
    }

    T random(T)() nothrow @nogc
    {
        pragma(inline, true);
        return rng.random!T();
    }
}
else
{
    import dcore.stdlib;
    import dcore.time;
    import dcore.process;
    
    enum RAND_MAX = 0x7fff;
    
    void init() nothrow @nogc
    {
        srand(cast(uint)seed());
    }
    
    void setSeed(uint s) nothrow @nogc
    {
        srand(s);
    }
    
    ulong seed() nothrow @nogc
    {
        return mix(clock(), time(null), processId());
    }

    /**
     * Returns pseudo-random integer between mi (inclusive) and ma (exclusive)
     */
    int randomInRange(int mi, int ma) nothrow @nogc
    {
        return (rand() % (ma - mi)) + mi;
    }
    
    /**
     * Returns pseudo-random floating-point number in 0..1 range
     */
    T random(T)() nothrow @nogc
    {
        T res = (rand() % RAND_MAX) / cast(T)RAND_MAX;
        return res;
    }
}
