/*
Copyright (c) 2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dcore.time;

struct DateTime
{
    int seconds;
    int minutes;
    int hours;
    int day;
    int month;
    int year;
    int dayInWeek;
    int dayInYear;
}

version(WebAssembly)
{
    // Not implemented
    
    // Fallback
    void init() nothrow @nogc
    {
    }
}
else version(FreeStanding)
{
    // Not implemented
    
    // Fallback
    void init() nothrow @nogc
    {
    }
}
else
{
    import dcore.c.time;
    
    void init() nothrow @nogc
    {
        dcore.c.time.init();
    }
    
    DateTime dateTimeFromTm(tm* timeInfo) pure nothrow @nogc
    {
        if (timeInfo is null)
            return DateTime();
        
        DateTime dateTime = {
            seconds: timeInfo.tm_sec,
            minutes: timeInfo.tm_min,
            hours: timeInfo.tm_hour,
            day: timeInfo.tm_mday,
            month: timeInfo.tm_mon,
            year: 1900 + timeInfo.tm_year,
            dayInWeek: timeInfo.tm_wday,
            dayInYear: timeInfo.tm_yday
        };
        
        return dateTime;
    }
    
    DateTime currentTimeLocal() nothrow @nogc
    {
        time_t t = time(null);
        tm timeInfo;
        localtime_s(&t, &timeInfo);
        return dateTimeFromTm(&timeInfo);
    }
    
    DateTime currentTimeUTC() nothrow @nogc
    {
        time_t t = time(null);
        tm timeInfo;
        gmtime_s(&t, &timeInfo);
        return dateTimeFromTm(&timeInfo);
    }
}
